### ISSUE TITLE
Delegation ‎- Eau De Vie

### ISSUE THREAD

**Issue by mrrttjd** [hmerritt/album-covers#3]
https://www.discogs.com/master/view/131397

**Comment by mrrttjd** [comment]
![Cover](https://user-images.githubusercontent.com/50893041/72771755-d08cb800-3bf9-11ea-86fd-1ed2ba6dd982.jpg)

**Comment by hmerritt** [comment]
## Added cover
https://github.com/hmerritt/album-covers/blob/master/covers/Delegation/%5B1979%5D%20Eau%20De%20Vie/cover.jpg
